[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ganaka"
version = "0.1.0"
description = "Python SDK for Ganaka"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "ShimoroJune", email = "shimorojune@gmail.com" }
]
keywords = ["sdk", "api", "trading"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pyright>=1.1.350",
    "ruff>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/shimorojune/ganaka"
Repository = "https://github.com/shimorojune/ganaka"
Issues = "https://github.com/shimorojune/ganaka/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/ganaka"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/README.md",
]

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
useLibraryCodeForTypes = true

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["ganaka"]

