export const icons = {
  sideNav_overview: "grommet-icons:overview",
  sideNav_shortlists: "tabler:list-details",
  sideNav_keys: "hugeicons:access",
  // ----------------------------------------
  create: "mdi:plus",
  menu: "humbleicons:dots-vertical",
  rename: "mdi:pencil",
  edit: "mdi:pencil",
  clone: "grommet-icons:clone",
  delete: "material-symbols:delete-outline",
  save: "teenyicons:save-solid",
  filter: "mynaui:filter",
  sort: "solar:sort-vertical-linear",
  search: "iconamoon:search-light",
  empty: "qlementine-icons:empty-slot-24",
  refresh: "ic:twotone-refresh",
  // ----------------------------------------
  timeline: "mdi:timeline-outline",
  shortlist: "tabler:list-details",
  strategy: "tabler:bulb",
  strategy_active: "tabler:bulb-filled",
  version: "qlementine-icons:version-control-16",
  create_version: "mdi:source-branch-plus",
};
