name: Publish Python SDK to PyPI

on:
    push:
        tags:
            - "sdk-v*"
    workflow_dispatch:
        inputs:
            version:
                description: "Version to publish (e.g., 0.1.0)"
                required: true
                type: string

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.9"

            - name: Update version if manual dispatch
              if: github.event_name == 'workflow_dispatch'
              run: |
                  cd packages/sdk
                  # Update version in pyproject.toml
                  sed -i 's/version = ".*"/version = "${{ github.event.inputs.version }}"/' pyproject.toml
                  # Update version in version.py
                  sed -i 's/__version__ = ".*"/__version__ = "${{ github.event.inputs.version }}"/' src/ganaka/version.py

            - name: Extract version from tag
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/sdk-v')
              run: |
                  TAG_VERSION=${GITHUB_REF#refs/tags/sdk-v}
                  cd packages/sdk
                  # Update version in pyproject.toml
                  sed -i "s/version = \".*\"/version = \"${TAG_VERSION}\"/" pyproject.toml
                  # Update version in version.py
                  sed -i "s/__version__ = \".*\"/__version__ = \"${TAG_VERSION}\"/" src/ganaka/version.py

            - name: Install build dependencies
              run: |
                  cd packages/sdk
                  uv pip install --system build hatchling

            - name: Build package
              run: |
                  cd packages/sdk
                  python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  packages-dir: packages/sdk/dist/
                  skip-existing: true
