name: Publish SDK

on:
  push:
    branches:
      - main
    paths:
      - "packages/sdk/**"
      - ".github/workflows/publish-sdk.yml"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "packages/sdk/pnpm-lock.yaml"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd packages/sdk
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          cd packages/sdk
          pnpm run build

      - name: Test
        run: |
          cd packages/sdk
          pnpm run test

      - name: Semantic Release
        run: |
          cd packages/sdk
          pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
